export const ActionTypes = {
    ADD_PRODUCTS:"ADD_PRODUCTS",
    EDIT_PRODUCTS:"EDIT_PRODUCTS",
    DELETE_PRODUCT:"DELETE_PRODUCTS",
    VIEW_PRODUCT:"VIEW_PRODUCT",
    LIST_PRODUCTS:"LIST_PRODUCTS",
    ADD_TEXT:"ADD_TEXT",
    GET_PRODUCT:"GET_PRODUCT"
}